version: "3.3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: ['/bin/bash', 'run.sh']
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
